config/routes.rb
Rails.application.routes.draw do
    resources :usuarios do
        resources :reviews, only: [:create, :update], module: :usuarios
    end        
    
    resources :animals do
        member do   
            get 'send_mail' => 'animals#sendmail'
        end
    end

    
    resource :usuario_sessions, only: [:create, :new, :destroy]

    root 'home#index'

end

app/models/animal.rb
class Animal < ActiveRecord::Base
    extend FriendlyId
    
    belongs_to :usuario
    
    mount_uploader :picture, PictureUploader
    friendly_id :name, use: [:slugged, :history]
    
	validates_presence_of :name, :specie, :slug
	validates_inclusion_of :specie, :in => %w(C D)  
    
    def self.most_recent
        order(created_at: :desc)
    end
end

app/models/review.rb
class Review < ActiveRecord::Base
    POINTS = (1..5).to_a
    belongs_to :reviewer, :class_name => 'Usuario'
    belongs_to :reviewed, :class_name => 'Usuario'
    
    validates_uniqueness_of :reviewer_id, scope: :reviewed_id
    validates_presence_of :points, :reviewer_id, :reviewed_id
    validates_inclusion_of :points, in: POINTS
    
    def self.stars
        (average(:points) || 0).round
    end
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	
	EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
    
    has_many :animals, dependent: :destroy

	# Validações
	validates_presence_of :nome, :sobrenome, :idade, :sexo, :email
	validates_inclusion_of :sexo, :in => %w(M F)
	validates_inclusion_of :perfil, :in => %w(O P)
	validates_numericality_of :idade, :greater_than_or_equal_to => 18
	validates_uniqueness_of :email

	validate :email_format

	has_secure_password

	def nome_completo
		"#{nome} #{sobrenome}"
	end

	def self.authenticate(email, password)
		usuario = find_by(email: email)
		if usuario.present?
			usuario.authenticate(password)
		end
	end

	private
	# Pode ser feita da sequinte forma validates_format_of :email, with: EMAIL_REGEXP
	def email_format
		errors.add(:email, :invalid) unless email.match(EMAIL_REGEXP)
	end
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
    before_action :set_animal, only: :show
    before_action :set_users_animal, only: [:edit, :update, :destroy]
    before_action :require_authentication, only: [:new, :edit, :create, :update, :destroy]
    
    def index
        @animals = Animal.most_recent
    end
    
	def new
        @animal = current_user.animals.build 
	end

	def create
        @animal = current_user.animals.build(animal_params)
        
		if @animal.save
			redirect_to @animal, notice: t('flash.notice.animal.create')
		else
			render action: :new
		end
	end

	def show
	end

	def edit
	end

	def update
		if @animal.update(animal_params)
			redirect_to @animal, notice: t('flash.notice.animal.update')
		else
			render action: :edit
		end
	end
    
    def destroy
        @animal.destroy
        redirect_to animals_path
    end
    
    def sendmail
        @animal = Animal.friendly.find(params[:id])
        @adopter = current_user
        Notifications.adoption(@animal, @adopter).deliver
        redirect_to animals_path, notice: 'Email enviado com sucesso'
    end
    
    def picture_url
        @animal.picture_url
    end
    
    def thumb_url
        @animal.picture.thumb.url
    end
    
    def has_picture?
        @animal.picture?
    end
    
	private

	def animal_params
        params.require(:animal).permit(:name, :specie, :picture)
	end
    
    def set_animal
        @animal = Animal.friendly.find(params[:id])
    end
    
    def set_users_animal
        @animal = current_user.animals.friendly.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@usuarios = Usuario.last(5).reverse
		@animals = Animal.last(5).reverse
	end
end

app/controllers/usuarios/reviews_controller.rb
class Usuarios::ReviewsController < ApplicationController
    before_filter :require_authentication
    
    def create
        review = user.reviews.find_or_initialize_by(reviewer_id: current_user.id)
        
        review.update!(review_params)
        
        head :ok
    end
    
    def update
        create
    end
    
    private
    def user
        @usuario ||= Usuario.find(params[:usuario_id])
    end
    
    def review_params
        params.require(:review).permit(:points)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
    before_action :require_no_authentication, only: [:new, :create]
    before_action :can_change, only: [:edit, :update]
    before_action :require_authentication, only: [:destroy]
    
	def new
		@usuario = Usuario.new #Variáveis de instância "@var" são acessíveis pela VIEW
	end

	def create
		@usuario = Usuario.new(user_params)
		if @usuario.save
			redirect_to @usuario, notice: 'Cadastro realizado com sucesso!'
		else
			render action: :new
		end
	end

	def show
        @usuario = Usuario.find(params[:id])
        if user_signed_in?
            @usuario_review = user.reviews.find_or_initialize_by(reviewer_id: current_user.id)
        end
	end

	def edit
		@usuario = Usuario.find(params[:id])
	end

	def update
		@usuario = Usuario.find(params[:id])
		if @usuario.update(user_params)
			redirect_to @usuario, notice: 'Usuário atualizado com sucesso!'
		else
			render action: :edit
		end
	end
    
    def destroy
        @usuario = Usuario.find(params[:id])
        @usuario.destroy
        user_session.destroy
        redirect_to root_path
    end
        
	private

	def user_params
		params.require(:usuario).permit(:nome, :sobrenome, :idade, :sexo, :email, :perfil, :endereco, :telefone, :password, :password_confirmation)
	end
    
    def user
        @user = Usuario.find(params[:id])
    end
    
    def can_change
        unless user_signed_in? && current_user == user
            redirect_to usuario_path(params[:id])
        end
    end
end

app/views/animals/_animal.html.erb
<div class="row">
    <div class="col-sm-offset-3 col-sm-4">
        <ul class="list-group">
                <div class="list-group-item">
                    <h4><%= link_to animal.name, animal %> <%= t'.owner_html', owner: animal.usuario.nome_completo %></h4>
                    <div>
                        <% if animal.picture.url != nil %>
                            <img src="<%= animal.picture.url %>" class="img-circle img-responsive" />
                        <% end %><br />
                    </div>
                    <div><p>Espécie: 
		              <% if animal.specie == "D" %>
			             Cachorro
		              <% else %>
			             Gato
	                  <% end %>
                    </p></div>
                    
                    <% if belongs_to_user(animal) %>
                    <ul class="container">
                        <li class="btn"><%= link_to t('.edit'), edit_animal_path(animal), class: 'btn btn-primary' %></li>
                        <li class="btn"><%= link_to t('.destroy'), animal_path(animal), class: 'btn btn-danger', method: :delete, data: {confirm: t('dialogs.destroy')}  %></li>
                    </ul>
                    <% end %>
                    <% if !belongs_to_user(animal) %>
                    <li class="btn"><%= link_to "Adotar", send_mail_animal_path(animal, current_user), class: 'btn btn-success' %></li>
                    
                    <% end %>
                </div>
        </ul>
    </div>
</div>

app/views/animals/_form.html.erb
<% if @animal.errors.any? %>
	<div id="error_explanation" class="col-sm-offset-4 col-sm-6 alert alert-danger fade in">
		<h4><font color="red"><%= t 'general.form_error' %></font></h4>
	</div>
<% end %>

<%= form_for(@animal, html: {class: 'form-horizontal'}) do |f| %>
	<div class="field form-group">
		<%= f.label :name, class: 'col-sm-offset-2 col-sm-2 control-label' %>
		<div class="col-sm-4">
			<%= f.text_field :name, class: 'form-control' %>
				<font color="red"><%= error_tag @animal, :name %></font>
		</div>
	</div>
    <div class="field form-group">
        <%= f.label :picture, class: 'col-sm-offset-2 col-sm-2 control-label' %>
        <div class="col-sm-4">
            <%= f.file_field :picture %>
            <%= error_tag @animal, :picture %>
        </div>
    </div>
	<div class="field form-group">
		<%= f.label :specie, class: 'col-sm-offset-2 col-sm-2 control-label'  %>
		<div class="col-sm-2 radio-inline">
			<%= f.radio_button :specie, 'D' %>
			<%= label :specie_dog, 'Cachorro' %><br />
			<%= f.radio_button :specie, 'C' %>
			<%= label :specie_cat, 'Gato' %> 
			<font color="red"><%= error_tag @animal, :specie %></font>
		</div>
	</div>

	<div class="actions form-group">
		<div class="col-sm-offset-4 col-sm-2">
            <%= f.submit nil, class: 'btn btn-primary'%><br /><br />
		</div>
	</div>
<% end %>

app/views/animals/index.html.erb
<div class="col-sm-offset-4 col-sm-8">
    <h3><%= t '.title' %></h3>
</div>

<%= render @animals %>

<div class="row">
    <div class="col-sm-offset-5 col-sm-2">
        <%= link_to t('links.back'), root_path, class: 'btn btn-success'  %>
    </div>
</div>
        

app/views/animals/show.html.erb
<div class="col-sm-offset-4 col-sm-4">
	<h2><%= t '.title', animal_name: @animal.name %></h2>
</div>

<div class="col-sm-offset-4 col-sm-4">
<ul class="list-group">
    <div>
        <% if @animal.picture.url != nil %>
            <img src="<%= @animal.picture.url %>" class="img-circle img-responsive" />
        <% end %><br />
    </div>
	<li class="btn">Espécie: 
		<% if @animal.specie == "D" %>
			Cachorro
		<% else %>
			Gato
	    <% end %>
</ul>
</div>

<div class="col-sm-offset-4 col-sm-4">
    <% if belongs_to_user(@animal) %>
	   <%= link_to t('.edit'), edit_animal_path(@animal), class: 'btn btn-primary' %>
    <% end %>
    <%= link_to t('links.back'), root_path, class: 'btn btn-success'  %>
</div>

app/views/home/index.html.erb
<div class="row">
    <div class="container_fluid">
    <div class="jumbotron text-center">
        <h1>Bem-vindo ao <span id="cor">PET</span>Adoption!</h1>
        <h4>Aqui você pode adotar ou oferecer um animal para adoção! <span class="glyphicon glyphicon-heart"></span></h4>
    </div>
    </div>
</div>

<div class="row">
    <div class="container-fluid"></div>
    <div class="container-fluid"></div>
    <div class="container col-lg-4 col-lg-offset-2 text-center">
        <h3><%= t '.title_usuario' %></h3>
        <table class="table table-responsive table-bordered table-striped">
            <% @usuarios.each do |usuario| %>
            <tr>
                <td class="text-capitalize"><%= link_to usuario.nome_completo, usuario %></td>
            </tr>
            <% end %>
        </table>
    </div>
    <div class="container col-lg-4 text-center">
        <h3><%= t '.title_animal' %></h3>
        <table class="table table-responsive table-bordered table-striped   ">
            <% @animals.each do |animal| %>
            <tr>
                <td class="text-capitalize"><%= link_to animal.name, animal %> - <%= animal.usuario.nome_completo %></td>
            </tr>
            <% end %>
        </table>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt">
<head>
  <title>PETadoption</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    "default" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<header>
	<% if user_signed_in? %>
		<%= render 'shared/user_navbar' %>
	<% else %>
		<%= render 'shared/visitor_navbar' %>
	<% end %>
	</header>
    
    <div class="row">
	<div id="notices" class="col-lg-offset-3 col-lg-4">
		<% if notice.present? %>
			<div class="alert alert-success">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <%= notice %>
            </div>
		<% end %>
		<% if alert.present? %>
			<div class="alert alert-danger">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <%= alert %>
            </div>
		<% end %>
    </div>
    </div>
    
    <div class="row">
        <%= yield %>
    </div>
	
</body>

</html>

app/views/notifications/adoption.html.erb
<h1><%= t '.title' %></h1>
<p>
    <%= t '.body', full_name: @animal.usuario.nome_completo, animal_name: @animal.name %>
</p>
<p>
    <%= t '.adopter_html', link: link_to(@adopter.nome_completo, usuario_url(@adopter)) %>
</p>

app/views/notifications/adoption.txt.erb
<%= t '.title' %>
<%= t '.body', full_name: @animal.usuario.nome_completo, animal_name: @animal.name %>
<%= t '.adopter', link: link_to(@usuario.nome_completo, usuario_path(@adopter)) %>

app/views/shared/_user_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<%= link_to "PETadoption", root_path, class: 'navbar-brand' %>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-right">
				<li><%= link_to usuario_sessions_path, method: :delete, class: 'btn btn-danger navbar-btn' do %>
                    <span class="glyphicon glyphicon-log-out"></span> Logout
                    <% end %>
                </li>
			</ul>
			<ul class="nav navbar-right">
				<li><%= link_to usuario_path(current_user), class: 'btn btn-danger navbar-btn' do %>
                    <span class="glyphicon glyphicon-user"></span> Meu Perfil
                    <% end %>
                </li>
			</ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown btn"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Animais <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><%= link_to t('layout.new_animal'), new_animal_path%></li>
                        <li><%= link_to t('layout.list_animal'), animals_path%></li>
                    </ul>
                </li>
            </ul>
		</div>
	</div>
</nav>

app/views/usuario_sessions/new.html.erb
<% if @usuario_session.errors.has_key? :base %>
	<div class="error_explanation col-lg-offset-2 col-lg-8 alert alert_danger fade in">
		<%= @usuario_session.errors[:base].join(', ') %>
	</div>
<% end %>

<div class="row">
<div class="container col-lg-offset-2 col-lg-8 text-center">
	<div class="jumbotron">
        <h2><%= t '.title' %></h2>
        
        <div class="row">
            <%= form_for(@usuario_session, html: {class: 'form-horizontal'}) do |f| %>
                <div class="field form-group">
                    <div class="col-lg-6 col-lg-offset-3">
                        <%= f.text_field :email, class: 'form-control', :placeholder => 'Email' %>
                            <font color="red"><%= error_tag @usuario_session, :email %></font>
                    </div>
                </div>
                <div class="field form-group">
                    <div class="col-lg-6 col-lg-offset-3">
                        <%= f.password_field :password, class: 'form-control', :placeholder => 'Senha' %>
                            <font color="red"><%= error_tag @usuario_session, :password %></font>
                    </div>
                </div>
                <div class="actions form-group">
                    <div class="col-lg-offset-5 col-lg-2">
                        <%= f.submit nil, class: 'btn btn-success'%><br /><br />
                    </div>
                </div>

                <div class="col-lg-8 col-lg-offser-4 text-center">
                    <small>Ainda não faz parte do PETadoption?</small> 
                    <%= link_to t('.sign_up'), new_usuario_path, class: 'btn btn-success' %>
                </div>
            <% end %>
        </div>
        
    </div>
</div>
</div>

app/views/usuarios/_form.html.erb
<% if @usuario.errors.any? %>
	<div id="error_explanation" class="col-sm-offset-4 col-sm-4 alert alert-danger fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		<h4><%= t 'general.form_error' %></h4>
	</div>
<% end %>

<div class="row">
    <div class="col-lg-12">
<%= form_for(@usuario, html: {class: 'form-horizontal'}) do |f| %>
	<div class="field form-group">
		<%= f.label :nome, class: 'col-sm-offset-2 col-sm-2 control-label' %>
		<div class="col-sm-4">
			<%= f.text_field :nome, class: 'form-control' %>
				<font color="red"><%= error_tag @usuario, :nome %></font>
		</div>
	</div>
	<div class="field form-group">
		<%= f.label :sobrenome, class: 'col-sm-offset-2 col-sm-2 control-label'  %>
		<div class="col-sm-4">
			<%= f.text_field :sobrenome, class: 'form-control' %>
			<font color="red"><%= error_tag @usuario, :sobrenome %></font>
		</div>
	</div>
	<div class="field form-group">
		<%= f.label :idade, class: 'col-sm-offset-2 col-sm-2 control-label'  %>
		<div class="col-sm-2">
			<%= f.number_field :idade, class: 'form-control' %>
			<font color="red"><%= error_tag @usuario, :idade %></font>
		</div>
	</div>
	<div class="field form-group">
		<%= f.label :sexo, class: 'col-sm-offset-2 col-sm-2 control-label'  %>
		<div class="col-sm-2 radio-inline">
			<%= f.radio_button :sexo, 'M' %>
			<%= label :sexo_M, 'Masculino'%><br />
			<%= f.radio_button :sexo, 'F' %>
			<%= label :sexo_F, 'Feminino'%> 
			<font color="red"><%= error_tag @usuario, :sexo %></font>
		</div>
	</div>
	<div class="field form-group">
		<%= f.label :email, class: 'col-sm-offset-2 col-sm-2 control-label'  %>
		<div class="col-sm-4">
			<%= f.email_field :email, class: 'form-control' %>
			<font color="red"><%= error_tag @usuario, :email %></font>
		</div>
	</div>
	<div class="field form-group">
		<%= f.label :perfil, class: 'col-sm-offset-2 col-sm-2 control-label'  %>
		<div class="col-sm-4 radio-inline">
			<%= f.radio_button :perfil, 'P' %>
			<%= label :perfil_P, 'Pessoa Física'%><br />
			<%= f.radio_button :perfil, 'O' %>
			<%= label :perfil_O, 'ONG' %> 
			<font color="red"><%= error_tag @usuario, :perfil %></font>
		</div>
	</div>
	<div class="field form-group">
		<%= f.label :endereco, class: 'col-sm-offset-2 col-sm-2 control-label'  %>
		<div class="col-sm-4">
			<%= f.text_field :endereco, class: 'form-control' %>
			<font color="red"><%= error_tag @usuario, :endereco %></font>
		</div>
	</div>
	<div class="field form-group">
		<%= f.label :telefone, class: 'col-sm-offset-2 col-sm-2 control-label'  %>
		<div class="col-sm-4">
			<%= f.telephone_field :telefone, class: 'form-control' %>
			<font color="red"><%= error_tag @usuario, :telefone %></font>
		</div>
	</div>
	<div class="field form-group">
		<%= f.label :password, class: 'col-sm-offset-2 col-sm-2 control-label'  %>
		<div class="col-sm-4">
			<%= f.password_field :password, class: 'form-control' %>
			<font color="red"><%= error_tag @usuario, :password %></font>
		</div>
	</div>
	<div class="field form-group">
		<%= f.label :password_confirmation, class: 'col-sm-offset-2 col-sm-2 control-label'  %>
		<div class="col-sm-4">
			<%= f.password_field :password_confirmation, class: 'form-control' %>
			<font color="red"><%= error_tag @usuario, :password_confirmation %></font>
		</div>
	</div>
	<div class="actions form-group">
		<div class="col-sm-offset-4 col-sm-2">
			<%= f.submit nil, class: 'btn btn-primary'%><br /><br />
		</div>
	</div>
<% end %>
        </div>
</div>

app/views/usuarios/_review.html.erb
<section class="review">
    <% if user_signed_in? %>
    <%= form_for [review.reviewed, review], remote: true do |f| %> <!-- review.REVIEWED para pegar o user.id de quem está-->
            <% Review::POINTS.each do |point| %>                   <!-- sendo editado-->
                <%= f.radio_button :points, point %>
                <%= f.label :points, point, value: point %>
            <% end %>
            <%= f.submit %>
        <% end %>
    <% else%>
        <span class="login_required">
            <% t('.login_to_review') %>
        </span>
    <% end %>
</section>
    

app/views/usuarios/new.html.erb
<div id="wrap">
    <div class="col-sm-offset-4 col-sm-8">
        <h2><%= t '.title' %></h2>
    </div>

    <%= render 'form' %>

    <div class="row">
        <div class="container">
            <div class="col-sm-offset-5 col-sm-2">
                <%= link_to t('links.back'), root_path, class: 'btn btn-success'  %>
            </div>
        </div>
    </div>
</div>

app/views/usuarios/show.html.erb
<div class="row">
    <div class="col-sm-offset-4 col-sm-4">
        <div class="panel-group">
            <div class="panel panel-primary">
                <div class="panel panel-heading"><h2><%= t '.title', user_name: @usuario.nome_completo %></h2>
                </div>
                
                    <div class="table-responsive">
                    <table class="table table-striped">
                        <tr>
                            <td><%= t '.idade', idade: @usuario.idade%></td>
                        </tr>
                        <tr><td>Sexo: 
                            <% if @usuario.sexo == "F" %>
                                Feminino
                            <% else %>
                                Masculino
                            <% end %>
                        </td></tr>
                        <tr><td><%= t '.email', email: @usuario.email%></td></tr>
                        <tr><td>Perfil: 
                            <% if @usuario.perfil == "O" %>
                                ONG
                            <% else %>
                                Pessoa Física
                            <% end %>
                        </td></tr>
                        <tr><td><%= t '.endereco', endereco: @usuario.endereco%></td></tr>
                        <tr><td><%= t '.telefone', telefone: @usuario.telefone%></td></tr>
                    </table>
                    </div>
                <div class="panel-footer">
                    <p class="pull-left"><%= render partial: 'review', object: @usuario_review %></p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-sm-offset-4 col-sm-4">
    <% if user_signed_in? && current_user == Usuario.find(params[:id]) %>
	   <%= link_to t('.edit'), edit_usuario_path(@usuario), class: 'btn btn-primary' %>
    <%= link_to t('.delete'), usuario_path(@usuario), class: 'btn btn-danger', method: :delete, data: {confirm: t('dialogs.destroy')} %>
    <% end %>
    <%= link_to t('links.back'), root_path, class: 'btn btn-success' %>
</div>